version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    container_name: postgresql-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=equine-training-tracker-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  rest-api:
    image: edbentho/bransby-api:v1.0.1
    build:
      context: ./
    container_name: rest-api
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=equine-training-tracker-db
      - DATASOURCE=jdbc:postgresql://postgresql_database:5432/
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_database

volumes:
  database-data:
    driver: azure_file
    driver_opts:
      share_name: bransbyshare
      storage_account_name: bransbystorage