spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE}${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-west-2.amazonaws.com/${COGNITO_USER_POOL}
          jwk-set-uri: https://cognito-idp.eu-west-2.amazonaws.com/${COGNITO_USER_POOL}/.well-known/jwks.json
